# Equal-Weight S&P 500 Index Fund

## Introduction & Library Imports

The S&P 500 is the world's most popular stock market index. The largest fund that is benchmarked to this index is the SPDR® S&P 500® ETF Trust. It has more than US$250 billion of assets under management.

The goal of this section of the course is to create a Python script that will accept the value of your portfolio and tell you how many shares of each S&P 500 constituent you should purchase to get an equal-weight version of the index fund.

## Library Imports

The first thing we need to do is import the open-source software libraries that we'll be using in this tutorial.

In [1]:
import numpy as np
import pandas as pd
import requests
import xlsxwriter
import math
import yfinance as yf

## Importing Our List of Stocks

The next thing we need to do is import the constituents of the S&P 500.

These constituents change over time, so in an ideal world you would connect directly to the index provider (Standard & Poor's) and pull their real-time constituents on a regular basis.

Paying for access to the index provider's API is outside of the scope of this course. 

There's a static version of the S&P 500 constituents available here. [Click this link to download them now](https://drive.google.com/file/d/1ZJSpbY69DVckVZlO9cC6KkgfSufybcHN/view?usp=sharing). Move this file into the `starter-files` folder so it can be accessed by other files in that directory.

Now it's time to import these stocks to our Jupyter Notebook file.

In [2]:
stocks = pd.read_csv('sp_500_stocks.csv')
stocks

    Ticker
0        A
1      AAL
2      AAP
3     AAPL
4     ABBV
..     ...
500    YUM
501    ZBH
502   ZBRA
503   ZION
504    ZTS

[505 rows x 1 columns]

## Acquiring an API Token

Now it's time to import our IEX Cloud API token. This is the data provider that we will be using throughout this course.

API tokens (and other sensitive information) should be stored in a `secrets.py` file that doesn't get pushed to your local Git repository. We'll be using a sandbox API token in this course, which means that the data we'll use is randomly-generated and (more importantly) has no cost associated with it.

[Click here](http://nickmccullum.com/algorithmic-trading-python/secrets.py) to download your `secrets.py` file. Move the file into the same directory as this Jupyter Notebook before proceeding.

--> IEX Clouds is deprecated, using yfinance (Yahoo Finance) for market data

In [ ]:
# from secrets import IEX_CLOUD_API_TOKEN
# Restart Kernel if file is not found

## Making Our First API Call

Now it's time to structure our API calls to IEX cloud. 

We need the following information from the API:

* Market capitalization for each stock
* Price of each stock

In [3]:
apple = 'AAPL'
appleStock = yf.Ticker(apple)
appleInfo = appleStock.info
print(appleInfo)

{'address1': 'One Apple Park Way', 'city': 'Cupertino', 'state': 'CA', 'zip': '95014', 'country': 'United States', 'phone': '(408) 996-1010', 'website': 'https://www.apple.com', 'industry': 'Consumer Electronics', 'industryKey': 'consumer-electronics', 'industryDisp': 'Consumer Electronics', 'sector': 'Technology', 'sectorKey': 'technology', 'sectorDisp': 'Technology', 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers exclusive original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.', 'fullTimeEmployees': 166000, 'companyOfficers': [{'maxAge': 1, 'name': 'Mr. Timothy D. Cook', 'age': 64, 'title': 'CEO & Director', 'yearBorn': 1961, 'fiscalYear': 2025, 'totalPay': 16759518, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Kevan  Parekh', 'age': 53, 'title': 'Senior VP & CFO', 'yearBorn': 1972, 'fiscalYear': 2025, 'totalPay': 4034174, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Sabih  Khan', 'age': 58, 'title': 'Senior VP & Chief Operating Officer', 'yearBorn': 1967, 'fiscalYear': 2025, 'totalPay': 5021905, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': "Ms. Deirdre  O'Brien", 'age': 58, 'title': 'Senior Vice President of Retail & People', 'yearBorn': 1967, 'fiscalYear': 2025, 'totalPay': 5037867, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Katherine L. Adams', 'age': 61, 'title': 'Senior VP of Government Affairs & Secretary', 'yearBorn': 1964, 'fiscalYear': 2025, 'totalPay': 5022482, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Ben  Borders', 'age': 44, 'title': 'Principal Accounting Officer', 'yearBorn': 1981, 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Suhasini  Chandramouli', 'title': 'Director of Investor Relations', 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Jennifer G. Newstead J.D.', 'age': 54, 'title': 'Senior VP & General Counsel', 'yearBorn': 1971, 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Kristin Huguet Quayle', 'title': 'Vice President of Worldwide Communications', 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Greg  Joswiak', 'title': 'Senior Vice President of Worldwide Marketing', 'fiscalYear': 2025, 'exercisedValue': 0, 'unexercisedValue': 0}], 'auditRisk': 2, 'boardRisk': 1, 'compensationRisk': 7, 'shareHolderRightsRisk': 1, 'overallRisk': 1, 'governanceEpochDate': 1777593600, 'compensationAsOfEpochDate': 1767139200, 'irWebsite': 'http://investor.apple.com/', 'executiveTeam': [], 'maxAge': 86400, 'priceHint': 2, 'previousClose': 271.35, 'open': 278.94, 'dayLow': 278.37, 'dayHigh': 287.21, 'regularMarketPreviousClose': 271.35, 'regularMarketOpen': 278.94, 'regularMarketDayLow': 278.37, 'regularMarketDayHigh': 287.21, 'dividendRate': 1.08, 'dividendYield': 0.39, 'exDividendDate': 1778457600, 'payoutRatio': 0.1259, 'fiveYearAvgDividendYield': 0.51, 'beta': 1.109, 'trailingPE': 33.915257, 'forwardPE': 29.292562, 'volume': 76013740, 'regularMarketVolume': 76013740, 'averageVolume': 44885765, 'averageVolume10days': 48483230, 'averageDailyVolume10Day': 48483230, 'bid': 280.16, 'ask': 288.5, 'bidSize': 2, 'askSize': 1, 'marketCap': 4109006274560, 'nonDilutedMarketCap': 4109006116320, 'fiftyTwoWeekLow': 193.25, 'fiftyTwoWeekHigh': 288.62, 'allTimeHigh': 288.62, 'allTimeLow': 0.049107, 'priceToSalesTrailing12Months': 9.101958, 'fiftyDayAverage': 261.2186, 'twoHundredDayAverage': 255.1833, 'trailingAnnualDividendRate': 1.04, 'trailingAnnualDividendYield': 0.003832688, 'currency': 'USD', 'tradeable': False, 'enterpriseValue': 4130719924224, 'profitMargins': 0.27152002, 'floatShares': 14662240621, 'sharesOutstanding': 14667688000, 'sharesShort': 134422787, 'sharesShortPriorMonth': 124192030, 'sharesShortPreviousMonthDate': 1773360000, 'dateShortInterest': 1776211200, 'sharesPercentSharesOut': 0.0092, 'heldPercentInsiders': 0.01642, 'heldPercentInstitutions': 0.65318, 'shortRatio': 3.24, 'shortPercentOfFloat': 0.0092, 'impliedSharesOutstanding': 14667688000, 'bookValue': 5.998, 'priceToBook': 46.70557, 'lastFiscalYearEnd': 1758931200, 'nextFiscalYearEnd': 1790467200, 'mostRecentQuarter': 1774656000, 'earningsQuarterlyGrowth': 0.194, 'netIncomeToCommon': 122575003648, 'trailingEps': 8.26, 'forwardEps': 9.56352, 'pegRatio': 2.44, 'lastSplitFactor': '4:1', 'lastSplitDate': 1598832000, 'enterpriseToRevenue': 9.15, 'enterpriseToEbitda': 25.821, '52WeekChange': 0.40851724, 'SandP52WeekChange': 0.2795812, 'lastDividendValue': 0.26, 'lastDividendDate': 1770595200, 'quoteType': 'EQUITY', 'currentPrice': 280.14, 'targetHighPrice': 355.0, 'targetLowPrice': 215.0, 'targetMeanPrice': 301.35953, 'targetMedianPrice': 302.5, 'recommendationMean': 1.875, 'recommendationKey': 'buy', 'numberOfAnalystOpinions': 42, 'totalCash': 68507000832, 'totalCashPerShare': 4.664, 'ebitda': 159975997440, 'totalDebt': 84710998016, 'quickRatio': 0.906, 'currentRatio': 1.07, 'totalRevenue': 451442016256, 'debtToEquity': 79.548, 'revenuePerShare': 30.534, 'returnOnAssets': 0.26229, 'returnOnEquity': 1.4147099, 'grossProfits': 216070995968, 'freeCashflow': 101090746368, 'operatingCashflow': 140222005248, 'earningsGrowth': 0.218, 'revenueGrowth': 0.166, 'grossMargins': 0.47862, 'ebitdaMargins': 0.35437, 'operatingMargins': 0.32275, 'financialCurrency': 'USD', 'symbol': 'AAPL', 'language': 'en-US', 'region': 'US', 'typeDisp': 'Equity', 'quoteSourceName': 'Nasdaq Real Time Price', 'triggerable': True, 'customPriceAlertConfidence': 'HIGH', 'epsTrailingTwelveMonths': 8.26, 'epsForward': 9.56352, 'epsCurrentYear': 8.76181, 'priceEpsCurrentYear': 31.972847, 'fiftyDayAverageChange': 18.921417, 'fiftyDayAverageChangePercent': 0.072435185, 'twoHundredDayAverageChange': 24.95671, 'twoHundredDayAverageChangePercent': 0.09779915, 'exchange': 'NMS', 'messageBoardId': 'finmb_24937', 'exchangeTimezoneName': 'America/New_York', 'exchangeTimezoneShortName': 'EDT', 'gmtOffSetMilliseconds': -14400000, 'market': 'us_market', 'esgPopulated': False, 'regularMarketChangePercent': 3.23936, 'regularMarketPrice': 280.14, 'shortName': 'Apple Inc.', 'longName': 'Apple Inc.', 'hasPrePostMarketData': True, 'firstTradeDateMilliseconds': 345479400000, 'postMarketChangePercent': -0.024990119, 'postMarketPrice': 280.07, 'postMarketChange': -0.070007324, 'regularMarketChange': 8.79001, 'regularMarketDayRange': '278.37 - 287.21', 'fullExchangeName': 'NasdaqGS', 'averageDailyVolume3Month': 44885765, 'fiftyTwoWeekLowChange': 86.890015, 'fiftyTwoWeekLowChangePercent': 0.44962493, 'fiftyTwoWeekRange': '193.25 - 288.62', 'fiftyTwoWeekHighChange': -8.47998, 'fiftyTwoWeekHighChangePercent': -0.029381126, 'fiftyTwoWeekChangePercent': 40.851723, 'dividendDate': 1770854400, 'earningsTimestamp': 1777579200, 'earningsTimestampStart': 1785441600, 'earningsTimestampEnd': 1785441600, 'earningsCallTimestampStart': 1777582800, 'earningsCallTimestampEnd': 1777582800, 'isEarningsDateEstimate': True, 'marketState': 'CLOSED', 'corporateActions': [], 'postMarketTime': 1777679999, 'regularMarketTime': 1777665602, 'sourceInterval': 15, 'exchangeDataDelayedBy': 0, 'averageAnalystRating': '1.9 - Buy', 'cryptoTradeable': False, 'displayName': 'Apple', 'trailingPegRatio': 2.5189}

In [4]:
tickers = stocks["Ticker"].dropna().tolist()
tickers = [ticker.strip() for ticker in tickers]

data = []

for ticker in tickers:
    stock = yf.Ticker(ticker)
    info = stock.info

    data.append({
        "Ticker": ticker,
        "Price": info.get("currentPrice"),
        "MarketCap": info.get("marketCap")
    })

stocksDf = pd.DataFrame(data)
# readable number
stocksDf ["MarketCap_Billion"] = stocksDf["MarketCap"] / 1e9

stocksDf

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ANSS"}}}
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: CMA"}}}
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HBI"}}}
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: HES"}}}
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: IPG"}}}
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: K"}}}
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: WBA"}}}

    Ticker   Price     MarketCap  MarketCap_Billion
0        A  114.52  3.236361e+10          32.363614
1      AAL   11.84  7.830800e+09           7.830800
2      AAP   58.93  3.555200e+09           3.555200
3     AAPL  280.14  4.109006e+12        4109.006275
4     ABBV  206.60  3.654263e+11         365.426311
..     ...     ...           ...                ...
500    YUM  158.36  4.377548e+10          43.775480
501    ZBH   82.90  1.604688e+10          16.046878
502   ZBRA  227.08  1.117045e+10          11.170452
503   ZION   63.26  9.304091e+09           9.304091
504    ZTS  114.16  4.819010e+10          48.190099

[505 rows x 4 columns]

## Using Batch API Calls to Improve Performance

Batch API calls are one of the easiest ways to improve the performance of your code.

This is because HTTP requests are typically one of the slowest components of a script.

Also, API providers will often give you discounted rates for using batch API calls since they are easier for the API provider to respond to.

IEX Cloud limits their batch API calls to 100 tickers per request. Still, this reduces the number of API calls we'll make in this section from 500 to 5 - huge improvement! In this section, we'll split our list of stocks into groups of 100 and then make a batch API call for each group.

In [ ]:
# possibly with yf.download but yfinance offers no direct batch-requests

## Calculating the Number of Shares to Buy

As you can see in the DataFrame above, we stil haven't calculated the number of shares of each stock to buy.

We'll do that next.

In [9]:
# investment
portfolio_size = 1000000
# Price as numeric
stocksDf["Price"] = pd.to_numeric(stocksDf["Price"], errors="coerce")
# clean invalid values
stocksDf = stocksDf.replace([np.inf, -np.inf], np.nan)

# how many of each stock of the index is bought based on the portfolio size (investment)
position_size = portfolio_size / len(stocksDf.index)
print(position_size)
stocksDf["Number of Shares to Buy"] = np.where(
    stocksDf["Price"] > 0,
    np.floor(position_size / stocksDf["Price"]),
    np.nan
)

stocksDf

1980.1980198019803

    Ticker   Price     MarketCap  MarketCap_Billion  Number of Shares to Buy
0        A  114.52  3.236361e+10          32.363614                     17.0
1      AAL   11.84  7.830800e+09           7.830800                    167.0
2      AAP   58.93  3.555200e+09           3.555200                     33.0
3     AAPL  280.14  4.109006e+12        4109.006275                      7.0
4     ABBV  206.60  3.654263e+11         365.426311                      9.0
..     ...     ...           ...                ...                      ...
500    YUM  158.36  4.377548e+10          43.775480                     12.0
501    ZBH   82.90  1.604688e+10          16.046878                     23.0
502   ZBRA  227.08  1.117045e+10          11.170452                      8.0
503   ZION   63.26  9.304091e+09           9.304091                     31.0
504    ZTS  114.16  4.819010e+10          48.190099                     17.0

[505 rows x 5 columns]

## Formatting Our Excel Output

We will be using the XlsxWriter library for Python to create nicely-formatted Excel files.

XlsxWriter is an excellent package and offers tons of customization. However, the tradeoff for this is that the library can seem very complicated to new users. Accordingly, this section will be fairly long because I want to do a good job of explaining how XlsxWriter works.

### Initializing our XlsxWriter Object

In [ ]:
# initialize writer with engine
writer = pd.ExcelWriter('recommended_trades.xlsx', engine='xlsxwriter')
# Specify tabs
stocksDf.to_excel(writer, 'Recommended Trades', index = False)

In [ ]:
print('Test')

### Creating the Formats We'll Need For Our `.xlsx` File

Formats include colors, fonts, and also symbols like `%` and `$`. We'll need four main formats for our Excel document:
* String format for tickers
* \\$XX.XX format for stock prices
* \\$XX,XXX format for market capitalization
* Integer format for the number of shares to purchase

In [ ]:
background_color = '#0a0a23'
font_color='#ffffff'

string_format = writer.book.add_format(
    {
        'font_color': font_color,
        'bg_color': background_color,
        'border': 1
    }
)

dollar_format = writer.book.add_format(
    {
        'num_format': '$0.00',
        'font_color': font_color,
        'bg_color': background_color,
        'border': 1
    }
)

integer_format = writer.book.add_format(
    {
        'num_format': '0',
        'font_color': font_color,
        'bg_color': background_color,
        'border': 1
    }
)

### Applying the Formats to the Columns of Our `.xlsx` File

We can use the `set_column` method applied to the `writer.sheets['Recommended Trades']` object to apply formats to specific columns of our spreadsheets.

Here's an example:

```python
writer.sheets['Recommended Trades'].set_column('B:B', #This tells the method to apply the format to column B
                     18, #This tells the method to apply a column width of 18 pixels
                     string_template #This applies the format 'string_template' to the column
                    )
```

In [ ]:
# writer.sheets['Recommended Trades'].set_column('A:A', 18, string_format)
# writer.sheets['Recommended Trades'].set_column('B:B', 18, string_format)
# writer.sheets['Recommended Trades'].set_column('C:C', 18, string_format)
# writer.sheets['Recommended Trades'].set_column('D:D', 18, string_format)
# writer.save()

This code works, but it violates the software principle of "Don't Repeat Yourself". 

Let's simplify this by putting it in 2 loops:

In [ ]:
column_formats = {
    'A': ['Ticker', string_format],
    'B': ['Stock Price', dollar_format],
    'C': ['Market Capitalization', dollar_format],
    'D': ['Number of Shares to Buy', integer_format]
}

for column in column_formats.keys():
    # format values
    writer.sheets['Recommended Trades'].set_column(f'{column}:{column}', 18, column_formats[column][1])
    # format headers
    writer.sheets('Recommended Trades').write(f'{column}1', column_formats[column][0], column_formats[column][1])

## Saving Our Excel Output

Saving our Excel file is very easy:

In [ ]:
writer.save()